db.createUser(
    {
        user:'volodymyr_antypenko',
        pwd:'cXROO3VXU0TFLj61',
        roles:[
            {
                role:'readWrite',
                db:'nodejs-express-db'
            }
        ]
    }
)